/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DaoGenerico;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Comentarios;
import model.Curtidas;
import model.Postagem;
import model.Usuario;

/**
 *
 * @author rodri
 */
public final class PostagemPVView extends javax.swing.JDialog {

    /**
     * Creates new form PostagemView
     */
    public Usuario logado = (Usuario) DaoGenerico.getInstance().BuscarUnicoWhere(Usuario.class, "usuCod", Long.parseLong(System.getProperty("ID")));
    public final Postagem pos;
    private final DefaultTableModel tblModelC, tblModelCom;
    private List<Curtidas> PC;
    private Curtidas curtida;
    private List<Comentarios> comentarios;

    public PostagemPVView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        pos = ((PerfilView) parent).post;

        SimpleDateFormat sdfd = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat sdft = new SimpleDateFormat("HH:mm:ss");

        jtPostagemT.setText(pos.getPostText());
        jlDataUser.setText("Postado por " + pos.getPostUsu().getUsuNome() + " em " + sdfd.format(pos.getPostData().getTime()) + " às " + sdft.format(pos.getPostData().getTime()));

        tblModelC = new DefaultTableModel(new String[]{"Usuário", "Data"}, 2) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        carregarTabelaCurtidas();
        
        tblModelCom = new DefaultTableModel(new String[]{"Usuário", "Comentário", "Data"}, 3) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        carregarTabelaComentarios();
    }
    
    private void carregarTabelaComentarios() {
        jTabComentarios.setVisible(false);
        tblModelCom.getDataVector().clear();
        comentarios = (List<Comentarios>) DaoGenerico.getInstance().BuscarTodosWhere(Comentarios.class, "comPost", pos);
        SimpleDateFormat sdfd = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat sdft = new SimpleDateFormat("HH:mm.ss");
        
        try {
            for (Comentarios com : comentarios) {
                tblModelCom.addRow(new Object[]{
                    com.getComUsu().getUsuNome(),
                    com.getComText(),
                    sdfd.format(com.getComData().getTime()) + " as " + sdft.format(com.getComData().getTime())
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }finally{
            jTabComentarios.setModel(tblModelCom);
            jTabComentarios.setVisible(true);
        }
    }

    public void carregarTabelaCurtidas() {
        jTabCurtidas.setVisible(false);
        tblModelC.getDataVector().clear();
        PC = (List<Curtidas>) DaoGenerico.getInstance().BuscarTodosWhere(Curtidas.class, "curPost", pos);
        SimpleDateFormat sdfd = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat sdft = new SimpleDateFormat("HH:mm.ss");
        try {
            for (Curtidas like : PC) {
                tblModelC.addRow(new Object[]{
                    like.getCurUsu().getUsuNome(),
                    sdfd.format(like.getCurData().getTime()) + " as " + sdft.format(like.getCurData().getTime())
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            jTabCurtidas.setModel(tblModelC);
            jTabCurtidas.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPostagemT = new javax.swing.JTextArea();
        jlDataUser = new javax.swing.JLabel();
        jbCurtir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabCurtidas = new javax.swing.JTable();
        jbDescurtir = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTabComentarios = new javax.swing.JTable();
        jbComentar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtComentarios = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jtPostagemT.setEditable(false);
        jtPostagemT.setColumns(20);
        jtPostagemT.setRows(5);
        jScrollPane1.setViewportView(jtPostagemT);

        jlDataUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jbCurtir.setText("Curtir");
        jbCurtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCurtirActionPerformed(evt);
            }
        });

        jTabCurtidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTabCurtidas);

        jbDescurtir.setText("Descurtir");
        jbDescurtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDescurtirActionPerformed(evt);
            }
        });

        jTabComentarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTabComentarios);

        jbComentar.setText("Comentar");
        jbComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComentarActionPerformed(evt);
            }
        });

        jtComentarios.setColumns(20);
        jtComentarios.setRows(5);
        jScrollPane3.setViewportView(jtComentarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbDescurtir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCurtir))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlDataUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbComentar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlDataUser, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbDescurtir)
                    .addComponent(jbCurtir)
                    .addComponent(jbComentar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCurtirActionPerformed
        // TODO add your handling code here:
        Map<String, Object> filtros = new HashMap<>();
        curtida = new Curtidas();
        filtros.put("curUsu", logado);
        filtros.put("curPost", pos);
        Curtidas curt = (Curtidas) DaoGenerico.getInstance().buscarUnicoWhereAnd(Curtidas.class, filtros);
        if (curt == null) {

            curtida.setCurCod(null);
            curtida.setCurData(Calendar.getInstance());
            curtida.setCurUsu(logado);
            curtida.setCurPost(pos);
            DaoGenerico.getInstance().inserir(curtida);
            JOptionPane.showMessageDialog(null, "Post curtido com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Você já curtiu esse post!");
        }
        carregarTabelaCurtidas();
    }//GEN-LAST:event_jbCurtirActionPerformed

    private void jbDescurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDescurtirActionPerformed
        // TODO add your handling code here:
        Map<String, Object> filtros = new HashMap<>();
        filtros.put("curUsu", logado);
        filtros.put("curPost", pos);
        Curtidas curt = (Curtidas) DaoGenerico.getInstance().buscarUnicoWhereAnd(Curtidas.class, filtros);
        if (curt != null) {

            DaoGenerico.getInstance().Deletar(curt);
            JOptionPane.showMessageDialog(null, "Post descurtido com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Você não curtiu esse post!");
        }
        carregarTabelaCurtidas();
    }//GEN-LAST:event_jbDescurtirActionPerformed

    private void jbComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComentarActionPerformed
        // TODO add your handling code here:
        try {
            Comentarios com = new Comentarios();
            com.setComCod(null);
            com.setComText(jtComentarios.getText());
            com.setComData(Calendar.getInstance());
            com.setComUsu(logado);
            com.setComPost(pos);
            DaoGenerico.getInstance().inserir(com);
            JOptionPane.showMessageDialog(null, "Inserido com sucesso");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao inserir " + e );
        }finally{
            jtComentarios.setText("");
            jtComentarios.requestFocus();
            carregarTabelaComentarios();
        }
    }//GEN-LAST:event_jbComentarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostagemPVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostagemPVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostagemPVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostagemPVView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PostagemPVView dialog = new PostagemPVView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTabComentarios;
    private javax.swing.JTable jTabCurtidas;
    private javax.swing.JButton jbComentar;
    private javax.swing.JButton jbCurtir;
    private javax.swing.JButton jbDescurtir;
    private javax.swing.JLabel jlDataUser;
    private javax.swing.JTextArea jtComentarios;
    private javax.swing.JTextArea jtPostagemT;
    // End of variables declaration//GEN-END:variables
}
